### ISSUE TITLE
Finite Pagination: When does it become a problem?

### ISSUE THREAD

**Issue by ValentinFunk** [deltaepsilon/firebase-paginator#14]
Hey, 

I was wondering at which point does Finite Pagination become a problem? Is the shallow endpoint restricted to some number of results?

**Comment by deltaepsilon** [comment]
The problem is that finite pagination requires a REST call for all of the ordered keys. It's a shallow call, so it only returns the keys... but I have no idea how it would perform with a 1-million-record collection :)

I've only tested it with a few hundred records at a time. I imagine it would work fine with tens of thousands of records and probably start to drag up around 100k... but that's a wild guess.

Good question!

**Comment by ValentinFunk** [comment]
I've tested it with 826k keys and i'm not seeing a huge difference in the response time so suppose it would work well into a 1 million record thing :) It does download 20MB of keys every time the count is done though, so it would probably make sense to do things a little differently for 1 mill :)

This is definitely good enough for my usecase though, suppose finite pagination will work fine for most scenarios. Thanks!

**Comment by deltaepsilon** [comment]
That's awesome! Thanks for the feedback. 20mb is crazy, and it's amazing that it survives that :)

Have you tried Firestore? It paginates much better, although counting all records still isn't supported.
