### ISSUE TITLE
Error importing project in NodeJS environment. 

### ISSUE THREAD

**Issue by ChristianTucker** [deltaepsilon/firebase-paginator#7]
I'm attempting to use this in a NodeJS project. I've tried ES5 and ES6 imports.

Version: `"firebase-paginator": "^1.0.13",`

```
var FirebasePaginator = require('firebase-paginator')
```

Results in the error:

```
FirebasePaginator is not a constructor on line 
const paginator = new FirebasePaginator(testRef, { pageSize: 5, finite: false });
```
adding `.default` to the import does not resolve the issue. 

----

```
import FirebasePaginator from 'firebase-paginator';
```

Causes the following error

```
_firebasePaginator2.default is not a constructor
```

**Comment by crivera** [comment]
i am getting the same issue:

"_firebasePaginator2.default is not a constructor"

but that is because I am using webpack to bundle my project for a react app which runs in a browser. 

so the window object will be available but I would like to use the module exports.

```
if (typeof window === 'object') {
  window.FirebasePaginator = FirebasePaginator;
} else if (typeof process === 'object') {
  module.exports = FirebasePaginator;
}
```
is there a way to have the module.exports invoked instead of the window part?

**Comment by ChristianTucker** [comment]
I'm using React as well, (react-native), and the `window.FirebasePaginator` is also not a valid constructor, is it working for you? @crivera

**Comment by crivera** [comment]
the window version wokred for me but it wasnt ideal... so i made my own fork which should work only with module.exports (ie node)

https://github.com/crivera/firebase-paginator

the only thing since I am using it in the browser i removed the axiom dependency... so we might wanna update something there... but just gimme a pullrequest and ill add it

**Comment by deltaepsilon** [comment]
I think I got it fixed:

https://github.com/deltaepsilon/firebase-paginator/commit/13bb075fabae398309a13250b2eca0654f3d844a

**Comment by deltaepsilon** [comment]
@crivera It worked fine with regular Node, but React uses JSDom, which has a window and a global. So I moved all of my testing over to JEST and figured out a better way to check for Node.js vs the browser.

Let me know if this doesn't work. Also, do you have an idea for how to split the code to it doesn't need Axios in the browser?
